name: yura_hiero
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  ## WIDGETS ##
  cupertino_icons: ^1.0.2

  ## YURA HIERO ##

  core:
    path: ../core
  widgets:
    path: ../widgets

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


#ASSETS
flutter:
  uses-material-design: true
  assets:
    - assets/

